### ISSUE TITLE
Support arm64

### ISSUE THREAD

**Issue by ruckc** [tryretool/retool-onpremise#104]
It would be extremely beneficial if retool's onprem supported linux/arm64 or darwin/arm64 architectures for alternative hardwares such as Raspberry PI and Mac Arm64 processors.

**Comment by corinz** [comment]
This is a requirement for us. Any plans to implement?

**Comment by bdjohnson529** [comment]
Thanks for surfacing @ruckc. This request has been raised in our community forum, and we're tracking it internally. I'm going to close this Github issue - any updates will be provided in our community forum

https://community.retool.com/t/build-a-retool-docker-image-for-arm-apple-m1-raspberry-pi/5663
