### ISSUE TITLE
Support trust-based (passwordless) authentication to PostgreSQL database

### ISSUE THREAD

**Issue by jawnsy** [tryretool/retool-onpremise#115]
# Overview

Retool only supports password-based authentication to PostgreSQL

# Background

I'm trying to use Retool's self-hosted installation in a Kubernetes cluster with Cloud SQL on Google Cloud. In order to avoid needing to create and rotate passwords, or handling key material, I am trying to use the [Cloud SQL authentication proxy](https://cloud.google.com/sql/docs/postgres/connect-kubernetes-engine).

The idea is that applications such as Retool should connect to the Cloud SQL Proxy (which, from Retool's perspective, appears as a PostgreSQL database) without supplying a password (I believe this uses [`trust` authentication](https://www.postgresql.org/docs/14/auth-trust.html)). The proxy then handles authentication with PostgreSQL using temporary OAuth2 credentials, and transparently handles credential rotation and encryption.

# Current behavior

Retool appears to require a password, and passing an empty password field in the Helm chart (the `config.postgresql.password` value set to an empty string results in an error: `Error running database migrations: SequelizeConnectionError: empty password returned by client`)

# Desired behavior

Retool should allow passwordless authentication.

**Comment by jawnsy** [comment]
Related: https://github.com/tryretool/retool-helm/issues/58

**Comment by bdjohnson529** [comment]
Thanks @jawnsy for surfacing. We're tracking this issue internally. Glad you got your instance working - please reach out to **support@retool.com** with any questions or concerns.
