### ISSUE TITLE
Push docker images to AWS ECR Public

### ISSUE THREAD

**Issue by glenthomas** [tryretool/retool-onpremise#118]
Hello, would you please publish the images you have in docker hub (https://hub.docker.com/u/tryretool), to AWS ECR public?
We are running your images using AWS container services and it would be a great improvement to have the Retool images available in AWS' public registry. This would avoid the docker hub pull limit and improve speed of transferring the image.

**Comment by bdjohnson529** [comment]
Hi @glenthomas, thanks for surfacing. We're tracking this request internally - in the meantime if you have questions or concerns please reach out to **support@retool.com**.
