### ISSUE TITLE
Error: write EPROTO (...) SSL routines:tls_process_ske_dhe:dh key too small

### ISSUE THREAD

**Issue by daniel4yg** [tryretool/retool-onpremise#122]
When testing connection for a "Postgres" resource and having "Connect using SSL" checked, the following error occurs:

`Unable to connect. Error: write EPROTO 139813594638272:error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small:../deps/openssl/openssl/ssl/statem/statem_clnt.c:2165:`

Docker-compose logs:

> "message":{"type":"CAUGHT_ERROR","stack":"Error: write EPROTO 140241452537792:error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small:../deps/openssl/openssl/ssl/statem/statem_clnt.c:2165:\n\n    at /snapshot/retool_development/backend/transpiled/server/controllers/resources/index.js\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"},"level":"warn"

**Retool host**: Ubuntu 20.04.4 LTS on AWS EC2
**Target DB**: AWS Aurora PostgreSQL with Postgres 11.13
**Retool versions**: 2.94.9 and 2.95.9 (checked on both)

SSL certificate and credentials are correct. `psql` connection from the server towards target DB results successful:

`psql "host=XYZ.eu-west-1.rds.amazonaws.com port=5432 dbname=ABC user=user"`

> psql (12.12 (Ubuntu 12.12-0ubuntu0.20.04.1), server 11.13)
> SSL connection (protocol: TLSv1.2, cipher: DHE-RSA-AES128-SHA, bits: 128, compression: off)

**Comment by BenjamynBaker** [comment]
Hi @daniel4yg! If you're still having issues here, can you write to support@retool.com via email or within the in-product chat?

I'll go ahead and close this issue since it's a product configuration issue - and not directly related to this repository!
