### ISSUE TITLE
Issues Deploying Latest 2.96.x+ on Heroku Self-Signed Certificate

### ISSUE THREAD

**Issue by mgan59** [tryretool/retool-onpremise#123]
Hi, currently running an instance of Retool on-premise in Heroku version `2.80.16`.  We are looking to upgrade, so the approach we figured first would be to at least get a new version running independently so we can see the new features and have confidence in how we proceed with the official update.  Or we'd also consider just building from scratch our retool UI if necessary.

I created a new environment (dyno+postgres) and pushed up  `2.96.4` (tried a release of `2.97.x-2.98.x` as well).  They gave  me the following error:

```
app[web.1]: Error running database migrations: SequelizeConnectionError: self signed certificate
heroku[web.1]: Process exited with status 1
heroku[web.1]: Starting process with command `/bin/sh -c ./docker_scripts/start_api.sh`
app[web.1]: not untarring the bundle
app[web.1]: [process service types] DB_CONNECTOR, DB_SSH_CONNECTOR, MAIN_BACKEND, JOBS_RUNNER, WORKFLOW_WORKER
app[web.1]: Failing checking database migrations
app[web.1]:
app[web.1]: ---------------------------
app[web.1]: -     EXITING RETOOL      -
app[web.1]: ---------------------------
```

I'm aware that Heroku requires `ssl` on [postgres](https://devcenter.heroku.com/changelog-items/2035) and I had read the Retool Self-Hosted Changelog previously and saw the instructions surrounding `POSTGRES_SSL_REJECT_UNAUTHORIZED` and `PGSSLMODE`.  Can confirm these are set as follows:

__ENV Variables__
```
PGSSLMODE=require
NODE_ENV=production
HEROKU_HOSTED=true
POSTGRES_SSL_REJECT_UNAUTHORIZED=false
LICENSE_KEY=secret
JWT_SECRET=secret
ENCRYPTION_KEY=secret
```

I was able to confirm that I can push up `2.80.16` I can get the app to run normally...  Curious if folks are having similar issues with Heroku deploys?  Is there other things I can try to debug the situation?  I used `heroku run /bin/bash --app <name>` to load a `shell` so I could double check the `env` to make sure values were mounted into the build.

**Comment by BenjamynBaker** [comment]
this should be resolved as of Nov-9-2022. Let me know if that's not the case.
