### ISSUE TITLE
Authentication Failure. Missing access token on non-protected page

### ISSUE THREAD

**Issue by leobeosab** [tryretool/retool-onpremise#126]
### Retool version: 2.83.26

Hey all, we have a weird issue where after a couple of weeks our non-protected app that works perfectly fine will start throwing `Authentication Failure. Missing access token` to any users that aren't logged into to retool essentially making it a protected page. 

The only way to fix this is to make some small change to the app and deploy it. Like removing a newline in a JS query. 

I checked everything I could but the error is coming from the retool_backend binary. I tried loading it up in Ghidra to see if I could get any more information. It doesn't look like it's directly referenced until the error happens. 

Any suggestions or code snippets around that 403 anyone could share? 

Thanks!

**Comment by BenjamynBaker** [comment]
Hi @leobeosab! If you're still having issues here, can you write to support@retool.com via email or within the in-product chat?

I'll go ahead and close this issue since it's a product issue - and not directly related to this repository!
