### ISSUE TITLE
Enabling readonlyRootFilesystem in ECS Fargate

### ISSUE THREAD

**Issue by dominic-oconnor** [tryretool/retool-onpremise#128]
I'd like to lock down the container in ECS Fargate and make the root file system read-only. Can you share what path or paths the `tryretool/backend` image and the retool app itself will expect to write to? (e.g. /tmp, ...)

**Comment by bdjohnson529** [comment]
Hi @dominic-oconnor, thanks for surfacing. There are features which would not work with this change. We're tracking this issue internally - please feel free to reach out to **support@retool.com** if you have any questions or concerns.
