### ISSUE TITLE
AWS One-click Deployment link broken

### ISSUE THREAD

**Issue by lifeofdave** [tryretool/retool-onpremise#133]
The [link](https://app.runx.dev/deploy-with-aws?url=https%3A%2F%2Fgithub.com%2Ftryretool%2Fretool-onpremise%2Fblob%2Fmaster%2Fopta%2Fopta.yaml&name=Retool) to deploy with AWS no longer works

**Comment by BenjamynBaker** [comment]
should be fixed now!
