### ISSUE TITLE
Error with aws fargate

### ISSUE THREAD

**Issue by fjcoulon** [tryretool/retool-onpremise#143]
While deploying to aws fargate i encounter the issues below 
"Error sending hot-shots message: Error: getaddrinfo ENOTFOUND host.docker.internal"
"Failed to init Redis for Multiplayer connect ECONNREFUSED 127.0.0.1:6379"
Not completely sure but it seems to be stopping the app to start, i'm assuming this since there is no other evident error.

**Comment by BenjamynBaker** [comment]
are you able to share the full logs and any additional AWS config details?

**Comment by fjcoulon** [comment]
Hi @BenjamynBaker Actually i was able to find the problem, in fact it was complicated to figure out but simple to solve. The issue is related with the NODE_ENV variable, we were trying to set all according with our environment, so it was set in 'development', this causes an extra process that requires redis to run and the server is stuck.

I was able to replicate locally, see capture below, this container was triggered using environment variable NODE_ENV=development

![image](https://user-images.githubusercontent.com/119377792/206825970-26a4af15-06b3-4211-85e6-11d6fb8abc5d.png)

In my case the issue is already solved so this can be closed.

**Comment by fjcoulon** [comment]
One more question, not sure if there is any documentation about this but what is the difference or particularities on the process service types MAIN_BACKEND, DB_CONNECTOR and JOBS_RUNNER. What are the implications of having all of them set in one container?
