### ISSUE TITLE
Problems deploying on Ubuntu 22 VM

### ISSUE THREAD

**Issue by johnd486** [tryretool/retool-onpremise#145]
I'm trying to deploy retool-onpremise to my Ubuntu 22.04.1 VM running on Virtualbox 6.1.4 on macOS 12.6.2.
I ran the command 
`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/tryretool/retool-onpremise/ssop/deploy-retool)" < <(echo "license-string-redacted")`
and got responses that docker could not be found. After a bit of digging I downloaded and installed `docker` (at version 20.10.22, then got a response that the command `docker-compose` could not be found. It seems to me that `docker-compose` is now rolled in to the `docker` CLI with the option `docker compose`?  After a bit more digging I cloned this git repository and noticed that shell scripts to download `docker` and `docker-compose` were contained. I ran `get-docker-compose.sh` and it downloaded ... something. I now have a command `docker-compose` installed in `/usr/local/bin`.

Having then run `wget https://raw.githubusercontent.com/tryretool/retool-onpremise/ssop/deploy-retool` to try to see what is actually going on, I then find
```
john@bid-db-test:~/retool/retool-onpremise$ ./deploy-retool 
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT   MEM %     NET I/O   BLOCK I/O   PIDS
ERROR: Couldn't find env file: /home/john/retool/retool-onpremise/docker.env

INFO: updating Retool!
ERROR: Couldn't find env file: /home/john/retool/retool-onpremise/docker.env
```
and then now I find files 
```
john@bid-db-test:~/retool/retool-onpremise$ ls -l docker.env*
-rw-rw-r-- 1 john john 1012 Jan  6 11:43 docker.env.template
-rw-rw-r-- 1 john john 1084 Jan  6 11:43 docker.env.testing
-rw-rw-r-- 1 john john  984 Jan  6 11:43 docker.env.trial
```
.... which one of these (if any) is the correct one please?

Seems to me this whole sequence needs a bit of a refresh.

**Comment by EvanK** [comment]
FWIW, I ran into a similar "command not found" issue with `docker-compose` in **Ubuntu 20**.

While the initial install script ran without issue, _attempting to restart_ the running instance failed after it attempted to invoke `docker-compose` rather than `docker compose`. I fixed it in the short term by updating the `local-trial` script itself to call `compose` as a sub-command of docker instead of a separate executable.

**Comment by azariz** [comment]
Same here, not compatible with the new docker compose on Ubuntu 20.22.
Also, aliasing docker-compose to docker compose doesnt work, since the script is calling specifically `/usr/local/bin/docker-compose`

```
ubuntu@ip-xx-xx-xx-xx:~$ /home/ubuntu/retool/retool-onpremise/local-trial
INFO: updating Retool!
/usr/local/bin/docker-compose: 1: Not: not found
```

**Comment by bdjohnson529** [comment]
Hi @johnd486, thanks for surfacing. We're tracking this issue internally - if you continue to run into roadblocks, please reach out to **support@retool.com**.
