### ISSUE TITLE
Enable mobile app building

### ISSUE THREAD

**Issue by unstppbl** [tryretool/retool-onpremise#154]
I installed on-premise solution, but can't find "Mobile App" option in "Create new" menu, is there any way to enable that feature?

**Comment by BenjamynBaker** [comment]
Hi @unstppbl! If you're still having issues here, can you write to support@retool.com via email or within the in-product chat?

**Comment by BenjamynBaker** [comment]
I'll go ahead and close this issue since it's a product configuration issue - and not directly related to this repository!
