### ISSUE TITLE
Self-hosted - AWS One click deploy failing (apostrophe on comment not escaped)

### ISSUE THREAD

**Issue by luislovera87** [tryretool/retool-onpremise#155]
Looks like the apostrophe on this comment is breaking the script because it's not escaped as the others.
https://github.com/tryretool/retool-onpremise/blob/2c236e6b37b6a2088004e364e04c93fa431e11c5/local-trial#L212

The logs stop there.

<img width="1138" alt="Screenshot 2023-02-24 at 1 31 36 AM" src="https://user-images.githubusercontent.com/22124020/221119210-145166cb-ca3d-4539-ae93-18c9f269f8df.png">

Then the CF fails when creating the EC2 Instance
<img width="1400" alt="Screenshot 2023-02-24 at 1 34 53 AM" src="https://user-images.githubusercontent.com/22124020/221119483-aeef2f9a-6221-4e8b-8b6b-2a8b2a1efd10.png">

**Comment by Quentin-Sch** [comment]
Stuck with this issue too
