### ISSUE TITLE
Deploy retool locally script not up to date

### ISSUE THREAD

**Issue by m-uppet** [tryretool/retool-onpremise#159]
Hi,

I just saw that the script at https://raw.githubusercontent.com/tryretool/retool-onpremise/ssop/deploy-retool that is used in the "deploy locally instructions" of the self-hosted retool main page seems out of date, as there is a comment '# TODO(hirday): change back to master'.

The postgres version used in this script is 9.6 as opposed to the 11.13 on the master branch. Is this difference expected ?

**Comment by bdjohnson529** [comment]
Hi @m-uppet. Thanks for surfacing, we are tracking this issue internally. I'm going to close this issue - if you have issues going forward, please reach out to **support@retool.com**.
