### ISSUE TITLE
Update ReTool Readme for GCP to the correct specs

### ISSUE THREAD

**Issue by magoodah** [tryretool/retool-onpremise#167]
Hi,

I've deployed Retool to GCE using an e2-medium instance (2 vCPU, 4GB RAM). However, while the application did run it would  keep dying every evening (at around the same time, about 6PM ET) since some process was pegging the CPU and RAM. 

I noticed that for all other platforms the recommended specs was a machine with 8GB RAM. I upgraded my VM to 8GBs of RAM and it's working perfectly fine now. 

I'm not sure if there is a reason that the minimum recommendation for GCP be 4GBs, but I'd suggest that that it be updated to 8GBs. Happy to create a Pull Request if there are no objections to that.

**Comment by BenjamynBaker** [comment]
Hi @magoodah! Thanks for flagging this issue. We have some updated GCE documentation coming soon that will include this!
