### ISSUE TITLE
Enforce SSL on Heroku

### ISSUE THREAD

**Issue by tovbinm** [tryretool/retool-onpremise#17]
When deployed on Heroku both HTTP and HTTPS endpoints are exposed. It would be great to have an option to enable server redirect of HTTP requests to HTTPS .

More info - https://help.heroku.com/J2R1S4T8/can-heroku-force-an-application-to-use-ssl-tls

**Comment by bdjohnson529** [comment]
Hi @tovbinm, thanks for surfacing. We're tracking this issue internally - please feel free to reach out to **support@retool.com** with any questions or concerns.
