### ISSUE TITLE
Expose helm chart repository

### ISSUE THREAD

**Issue by TheFrozenFire** [tryretool/retool-onpremise#2]
The way we consume helm charts is via the `helm dep` system, which consumes helm chart repositories of a given structure. You can expose the helm chart in this repository using the approach documented here: https://github.com/helm/helm/blob/master/docs/chart_repository.md#github-pages-example

**Comment by AustinMoninger** [comment]
We now have helm charts hosted in another repository here: https://github.com/tryretool/retool-helm
