### ISSUE TITLE
Create a local account 

### ISSUE THREAD

**Issue by Opswatch** [tryretool/retool-onpremise#38]
Hi 

We are testing retool locally on kubernetes and when we try to create a account locally the logs show the following error `{"requestId":"b50a84f2-cc61-49a1-a532-4e72554c0546","message":{"type":"DATABASE_ERROR","stack":"SequelizeDatabaseError: column \"sid\" does not exist\n    at Query.formatError (/snapshot/backend/node_modules/sequelize/lib/dialects/postgres/query.js:363:16)\n`
Do we need to create a account using a different method other than the ui?

**Comment by kentwalters** [comment]
Hey there. You don't need to create an account outside of the UI. This error indicates that Retool's Postgres database was improperly set up. In particular, the 'sid' column uses the postgres uuid-ossp extension, so if this is improperly installed the migrations may fail & this column won't exist. 

Are you running Retool's database in a pod or in a standalone database instance?

**Comment by Opswatch** [comment]
Im running it on a pod, just a simple local k3s kubernetes cluster, taking a look at the postgres logs other that the standard db boot up this is the only thing that it shows

`ERROR:  column "sid" does not exist at character 14HINT:  Perhaps you meant to reference the column "organization.id".`

**Comment by Opswatch** [comment]
Just to update this issue it was my fault, I switched the Postgres container to pull from AWS ECR ( to get around pull limits ), looks like it was a Bitnami one, their images are a bit special im guessing it was looking for a different admin user than what the usual postgres comes with, switching it back to a docker hub image worked fine, sadly not many 9.6.5 versions exist in ecr, ill close up this issue.
