### ISSUE TITLE
cloudformation template - AWS secrets manager

### ISSUE THREAD

**Issue by valery-zhurbenko** [tryretool/retool-onpremise#5]
The secrets output (RDS credentials, JWT...) copied to ECS task variables, which is exposed to employees that are  ECS "operators".
I guess you should implement AWS secrets manager with "ValueFrom" instead of "Value" in ECS task variables. https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data.html

**Comment by bdjohnson529** [comment]
Hi @valery-zhurbenko, thanks for surfacing. We are tracking this issue internally - please reach out to **support@retool.com** with any questions or concerns.
