### ISSUE TITLE
Unable to launch Retool on a Raspberry Pi

### ISSUE THREAD

**Issue by chrisvanberg** [tryretool/retool-onpremise#57]
Hello, I'm trying to host Retool on my Raspberry Pi (arm) and I couldn't make it work...

Raspberry Pi 4
Ram 8Go
OS Ubuntu 20.4

Do you have any idea ?
Thanks !

**Comment by alexwestreich** [comment]
We currently don't publish a build that supports the ARM architecture that Raspberry Pi's use, but may at some point in the future to help support M1 mac laptops

Community post for reference:
https://community.retool.com/t/build-a-retool-docker-image-for-arm-apple-m1-raspberry-pi/5663
