### ISSUE TITLE
Alternative base image options to allow for security patching and compliance

### ISSUE THREAD

**Issue by alathers** [tryretool/retool-onpremise#74]
We presently use retool, deployed on AWS.  The  backend image ships on Debian Buster, which gets flagged by Amazon's ECR registry scanner.  So far we have tried:
* Patching the image off of the lastest buster packages - result: 1Critical + 303 others
* Dist upgrading from buster to bullseye - result: 2High + 100 others
* Multi-stage build moving the retool bundle onto an amazonlinux image.  This has other challenges, as there are tons of library dependancies that fail, and some of the node modules don't port cleanly.  Reinstallation also fails, because several of the images are source from an internal npm repo so they can't be dynamically rebuilt.

I'm really fine with any of these options:
* An amazonlinux (or RHEL, centos whatever) based image that I can keep up to date myself
* Help getting the multi-stage build working.
* Anything else that helps my security scans pass so I don't to spend infinite hours justifying it away during audit season.

**Comment by bdjohnson529** [comment]
Hi @alathers, thanks for surfacing. We're tracking this issue internally - please feel free to reach out to **support@retool.com** with any questions or concerns.
