### ISSUE TITLE
Deploy to heroku button is missing key env variables

### ISSUE THREAD

**Issue by TechMasterElvy** [tryretool/retool-onpremise#86]
I used Deploy to heroku but the app was failing due to error `sql_error_code = 28000 FATAL: no pg_hba.conf entry for host "xxx" user "xxx", database "xxx", SSL off`

I looked up the docs and found that I was missing the following: 
* `HEROKU_HOSTED` set to `true`
* `LICENSE_KEY` - your Retool license key
* `PGSSLMODE` - set to require

Also, [official docs](https://docs.retool.com/docs/heroku) doesn't mention `LICENSE_KEY`

**Comment by bdjohnson529** [comment]
Hi @TechMasterElvy, thanks for surfacing. PR has been merged - please reach out to **support@retool.com** if you have any questions or concerns.
