### ISSUE TITLE
Launch Port Specification

### ISSUE THREAD

**Issue by chrisui** [tryretool/retool-onpremise#92]
Is there a way to launch retool (via start_api.sh) with a different port?

Context: Docker container, running within fargate where I'd like to use pre-allocated security group ports rather than create a new rule for the fixed 3000 port.

**Comment by lrascao-anchor** [comment]
+1 also interested in this answer

**Comment by jHumeLPL** [comment]
Yeah, it's nuts there isn't any documentation on this yet...  From my google searches, changing ports in docker is not easy (especially for someone who doesn't have any previous experience with Docker, like me, and probably a fair amount of people that are deploying this as well), so having the ReTool team supply some documentation or even a config function that makes changing the default port either before or after install clear and easy would be a huge help.

**Comment by fjcoulon** [comment]
Not an expert on this but perhaps using a custom port specification can do the trick, in my case, i was trying to run it locally in port 80 and I was able to do so.
![image](https://user-images.githubusercontent.com/119377792/206826858-0f84417d-3b9e-4007-9963-05511b1b01d4.png)

just used docker run <some stuff in between> -p "80:3000" <containerid>

**Comment by BenjamynBaker** [comment]
Hello! 

For the default docker-compose deploy, you can update the port mapping on this [line](https://github.com/tryretool/retool-onpremise/blob/master/docker-compose.yml#L28)! For example, you could update the mapping from `3000:3000` to a more desirable port, like `3001:3000` which would expose port 3001. 

Let us know if you're still having issues with this!
